import streamlit as st
from fpdf import FPDF
import pandas as pd
import random
from datetime import datetime, timedelta

st.set_page_config(page_title="MFS Professional", layout="wide")

# 1. Automatic Data Generator (6 Months)
def generate_auto_data(start_bal):
    data = []
    current_bal = start_bal
    date_direct = datetime(2026, 3, 1)
    
    for i in range(150):
        date_str = (date_direct - timedelta(days=i)).strftime("%d-%m-%Y")
        # Har mahine ki 1 tarikh ko Salary
        if i % 30 == 0:
            desc = "Salary - Tata Motors Limited"
            dep, wit = 80000.0, 0.0
        else:
            desc = random.choice(["UPI-Transfer", "ATM Cash", "Petrol Pump", "Amazon Pay", "Zomato"])
            dep, wit = 0.0, random.uniform(100, 5000)
        
        current_bal = current_bal + dep - wit
        data.append({"date": date_str, "desc": desc, "wit": wit, "dep": dep, "bal": current_bal})
    return data

# 2. UI Header
st.title("🏦 Mohit Financial Services")
st.info("Professional Bank Statement System")

name = st.text_input("Customer Name", "Mohit Kumar Rai")
bank_type = st.selectbox("Select Bank Style", ["AXIS BANK", "SBI", "HDFC"])
opening_bal = st.number_input("Opening Balance", value=100000.0)

if st.button("🚀 Generate 6 Months (150 Entries) Automatically"):
    st.session_state.auto_data = generate_auto_data(opening_bal)
    st.success("Data Generated! Ab niche se PDF download karein.")

# 3. PDF Function with Table & Layout
if "auto_data" in st.session_state:
    if st.button("📥 Download Professional PDF"):
        pdf = FPDF()
        pdf.add_page()
        
        # Bank Header (Logo Placeholder)
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, f"{bank_type} - OFFICIAL STATEMENT", 0, 1, 'C')
        pdf.set_font("Arial", '', 10)
        pdf.cell(0, 5, "Generated by Mohit Financial Services | 7047205959", 0, 1, 'C')
        pdf.ln(10)
        
        # Customer Detail Box
        pdf.set_fill_color(245, 245, 245)
        pdf.rect(10, 35, 190, 20, 'F')
        pdf.cell(0, 7, f"Customer: {name}", 0, 1)
        pdf.cell(0, 7, f"Period: Sept 2025 to March 2026", 0, 1)
        pdf.ln(10)
        
        # Table Header
        pdf.set_fill_color(50, 50, 50)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(25, 10, "Date", 1, 0, 'C', True)
        pdf.cell(85, 10, "Narration", 1, 0, 'C', True)
        pdf.cell(25, 10, "Withdrawal", 1, 0, 'C', True)
        pdf.cell(25, 10, "Deposit", 1, 0, 'C', True)
        pdf.cell(30, 10, "Balance", 1, 1, 'C', True)
        
        # Table Data
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", '', 8)
        for row in st.session_state.auto_data:
            pdf.cell(25, 7, row['date'], 1)
            pdf.cell(85, 7, row['desc'], 1)
            pdf.cell(25, 7, f"{row['wit']:.2f}" if row['wit']>0 else "", 1, 0, 'R')
            pdf.cell(25, 7, f"{row['dep']:.2f}" if row['dep']>0 else "", 1, 0, 'R')
            pdf.cell(30, 7, f"{row['bal']:.2f}", 1, 1, 'R')
            
        pdf.output("statement.pdf")
        with open("statement.pdf", "rb") as f:
            st.download_button("Click here to Save PDF", f, file_name="Bank_Statement.pdf")
            
